metadata {
  definition(name: "PIXEL Controller", namespace: "oliverspryn", author: "Oliver Spryn") {
    capability "Switch"
  }

  tiles(scale: 2) {
    standardTile ("switch", "device.switch", width: 6, height: 4, canChangeIcon: true, decoration: "flat") {
      state("off", label: '${currentValue}', action: "switch.on",
            icon: "st.switches.switch.off", backgroundColor: "#ffffff")
      state("on", label: '${currentValue}', action: "switch.off",
            icon: "st.switches.switch.on", backgroundColor: "#00a0dc")
    }
    
    main("switch")
    details(["switch"])
  }
  
  preferences {
    input(name: "external", required: true, type: "enum", displayDuringSetup: true,
      options: [
        "Internal",
        "External"
      ],
      title: "Internal or External to your Network")
            
    input(name: "url", required: true, type: "text", displayDuringSetup: true,
      title: "URL (External) or IP Address (Internal)",
      description: "Enter the external URL or internal IP address to your PIXEL device")
            
    input(name: "image", required: true, type: "enum", displayDuringSetup: true,
      options : [
        "/animations/rshifter.gif"                     : "[Animated] 2048",
        "/animations/pattern.gif"                      : "[Animated] Abstract Art 1",
        "/animations/triopy.gif"                       : "[Animated] Abstract Art 2",
        "/animations/girlacordion.gif"                 : "[Animated] Accordion",
        "/animations/0aascension32.gif"                : "[Animated] Anime",
        "/animations/zarcade.gif"                      : "[Animated] Arcade Games",
        "/animations/sfighting.gif"                    : "[Animated] Argument",
        "/animations/arrowfinal.gif"                   : "[Animated] Arrows 1",
        "/animations/arrows.gif"                       : "[Animated] Arrows 2",
        "/animations/amigaball.gif"                    : "[Animated] Ball 1",
        "/animations/orangeball.gif"                   : "[Animated] Ball 2",
        "/animations/rwhiteball.gif"                   : "[Animated] Ball 3",
        "/animations/triball.gif"                      : "[Animated] Ball 4",
        "/animations/balloon2.gif"                     : "[Animated] Balloon 1",
        "/animations/balloonfloating.gif"              : "[Animated] Balloon 2",
        "/animations/mbats.gif"                        : "[Animated] Bat Colony",
        "/animations/bike.gif"                         : "[Animated] Bike",
        "/animations/yellowbird.gif"                   : "[Animated] Bird",
        "/animations/finaldirigible.gif"               : "[Animated] Blimp",
        "/animations/sboxergreen.gif"                  : "[Animated] Boxer 1",
        "/animations/sboxerpink.gif"                   : "[Animated] Boxer 2",
        "/animations/bubbles.gif"                      : "[Animated] Bubbles",
        "/animations/butterflies_clouds.gif"           : "[Animated] Butterflies 1",
        "/animations/mbutterflies_black.gif"           : "[Animated] Butterflies 2",
        "/animations/candy.gif"                        : "[Animated] Candy",
        "/animations/0petit_kitty.gif"                 : "[Animated] Cat 1",
        "/animations/cat.gif"                          : "[Animated] Cat 2",
        "/animations/cattail.gif"                      : "[Animated] Cat 3",
        "/animations/cloud1.gif"                       : "[Animated] Cloudy",
        "/animations/lighter_fire2_lighter.gif"        : "[Animated] Cigarette Lighter",
        "/animations/msmoking.gif"                     : "[Animated] Cigarette Smoke",
        "/animations/0clockworks.gif"                  : "[Animated] Clock Gears",
        "/animations/worm.gif"                         : "[Animated] Color Worm",
        "/animations/crosshatch.gif"                   : "[Animated] Colored Geometry",
        "/animations/colortiles.gif"                   : "[Animated] Colored Tiles 1",
        "/animations/fliptile.gif"                     : "[Animated] Colored Tiles 2",
        "/animations/usleepsheep.gif"                  : "[Animated] Counting Sheep",
        "/animations/scrowd.gif"                       : "[Animated] Crowd",
        "/animations/rainmbowcube.gif"                 : "[Animated] Cube",
        "/animations/demo.gif"                         : "[Animated] Demo Collage",
        "/animations/dogtable.gif"                     : "[Animated] Dog 1",
        "/animations/postman_dog.gif"                  : "[Animated] Dog 2",
        "/animations/woofwoof.gif"                     : "[Animated] Dog 3",
        "/animations/dynaboom.gif"                     : "[Animated] Dynamite",
        "/animations/earth.gif"                        : "[Animated] Earth",
        "/animations/horde.gif"                        : "[Animated] Enemy Horde",
        "/animations/face.gif"                         : "[Animated] Face",
        "/animations/farmer.gif"                       : "[Animated] Farmer",
        "/animations/0fire.gif"                        : "[Animated] Fireplace",
        "/animations/firehalf.gif"                     : "[Animated] Fire 1",
        "/animations/firewhole.gif"                    : "[Animated] Fire 2",
        "/animations/anglefish.gif"                    : "[Animated] Fish 1",
        "/animations/yellowfish.gif"                   : "[Animated] Fish 2",
        "/animations/zaquarium.gif"                    : "[Animated] Fish 3",
        "/animations/fishswimming.gif"                 : "[Animated] Fishbowl",
        "/animations/fishmen.gif"                      : "[Animated] Fisherman",
        "/animations/float.gif"                        : "[Animated] Floating Particles",
        "/animations/colorblend.gif"                   : "[Animated] Fluid Colors",
        "/animations/rspray.gif"                       : "[Animated] Fountain",
        "/animations/gameboy1.gif"                     : "[Animated] Gameboy 1",
        "/animations/gameboy2.gif"                     : "[Animated] Gameboy 2",
        "/animations/ghost.gif"                        : "[Animated] Ghost",
        "/animations/greendot.gif"                     : "[Animated] Green Laser",
        "/animations/guitar.gif"                       : "[Animated] Guitar",
        "/animations/heman.gif"                        : "[Animated] He Man",
        "/animations/heartbeat.gif"                    : "[Animated] Heartbeat",
        "/animations/kung_fu.gif"                      : "[Animated] Kung Fu",
        "/animations/lightning.gif"                    : "[Animated] Lightning 1",
        "/animations/storm_city.gif"                   : "[Animated] Lightning 2",
        "/animations/flower.gif"                       : "[Animated] Link",
        "/animations/flow.gif"                         : "[Animated] Magma Flow 1",
        "/animations/fountain.gif"                     : "[Animated] Magma Flow 2",
        "/animations/kart.gif"                         : "[Animated] Mario Kart 1",
        "/animations/kart2.gif"                        : "[Animated] Mario Kart 2",
        "/animations/nmoai.gif"                        : "[Animated] Moai",
        "/animations/coast.gif"                        : "[Animated] Motorcycle",
        "/animations/fuji.gif"                         : "[Animated] Mount Fuji",
        "/animations/0nightdrive.gif"                  : "[Animated] Night Drive",
        "/animations/0anightmare32.gif"                : "[Animated] Nightmare",
        "/animations/0pacman.gif"                      : "[Animated] Pacman",
        "/animations/0pacghosts.gif"                   : "[Animated] Pacman Ghosts",
        "/animations/0pharmacy.gif"                    : "[Animated] Pharmacy",
        "/animations/mfrog_mixedmedia.gif"             : "[Animated] Pond Frog",
        "/animations/pong.gif"                         : "[Animated] Pong",
        "/animations/postman.gif"                      : "[Animated] Postman",
        "/animations/girlpraying.gif"                  : "[Animated] Praying 1",
        "/animations/spraying.gif"                     : "[Animated] Praying 2",
        "/animations/racecar.gif"                      : "[Animated] Race Car",
        "/animations/0rain.gif"                        : "[Animated] Raining 1",
        "/animations/rainfast.gif"                     : "[Animated] Raining 2",
        "/animations/bluerobin.gif"                    : "[Animated] Robin",
        "/animations/0robotfactory.gif"                : "[Animated] Robot Factory",
        "/animations/boat.gif"                         : "[Animated] Sailing",
        "/animations/lines.gif"                        : "[Animated] Scrolling Lines",
        "/animations/shark.gif"                        : "[Animated] Shark",
        "/animations/usnail.gif"                       : "[Animated] Snail",
        "/animations/usnowy.gif"                       : "[Animated] Snow",
        "/animations/usnowman2.gif"                    : "[Animated] Snowman",
        "/animations/yship.gif"                        : "[Animated] Space Ship",
        "/animations/shuttle.gif"                      : "[Animated] Space Shuttle",
        "/animations/mspider_blue.gif"                 : "[Animated] Spider 1",
        "/animations/mspider_greenweb.gif"             : "[Animated] Spider 2",
        "/animations/squid.gif"                        : "[Animated] Squid",
        "/animations/0glitter.gif"                     : "[Animated] Star 1",
        "/animations/bluestar.gif"                     : "[Animated] Star 2",
        "/animations/rstarfield.gif"                   : "[Animated] Star 3",
        "/animations/rstarburst.gif"                   : "[Animated] Star 4",
        "/animations/stars.gif"                        : "[Animated] Star 5",
        "/animations/sunny.gif"                        : "[Animated] Sunny",
        "/animations/sunset.gif"                       : "[Animated] Sunset",
        "/animations/0matrix.gif"                      : "[Animated] The Matrix",
        "/animations/train.gif"                        : "[Animated] Train",
        "/animations/mchest.gif"                       : "[Animated] Treasure Chest 1",
        "/animations/treasurechest.gif"                : "[Animated] Treasure Chest 2",
        "/animations/0tree.gif"                        : "[Animated] Tree 1",
        "/animations/sakura.gif"                       : "[Animated] Tree 2",
        "/animations/tv_static.gif"                    : "[Animated] TV Static",
        "/animations/ufo.gif"                          : "[Animated] UFO",
        "/animations/samus.gif"                        : "[Animated] Video Game",
        "/animations/quest.gif"                        : "[Animated] Warrior 1",
        "/animations/run.gif"                          : "[Animated] Warrior 2",
        "/animations/warrior.gif"                      : "[Animated] Warrior 3",
        "/animations/water_tub.gif"                    : "[Animated] Water 1",
        "/animations/waterflow.gif"                    : "[Animated] Water 2",
        "/animations/windmill.gif"                     : "[Animated] Windmill",
        "/animations/0wizardcity.gif"                  : "[Animated] Wizard",
        
        
        
        "/clock"                                       : "[Special] Clock",
      
      
      
        "/still/abottom-row-icon.png"                  : "[Still] Alien 1",
        "/still/afygar-icon.png"                       : "[Still] Alien 2",
        "/still/galien32.png"                          : "[Still] Alien 3",
        "/still/garwor-icon.png"                       : "[Still] Alien 4",
        "/still/0aagreenmonster32.png"                 : "[Still] Alien 5",
        "/still/purple_alien.png"                      : "[Still] Alien 6",
        "/still/apurple-alien-icon.png"                : "[Still] Alien 7",
        "/still/aaligator-icon.png"                    : "[Still] Alligator",
        "/still/american_flag.png"                     : "[Still] American Flag",
        "/still/apple.png"                             : "[Still] Apple 1",
        "/still/aapple-bonus-icon.png"                 : "[Still] Apple 2",
        "/still/bacon.png"                             : "[Still] Bacon",
        "/still/bball.png"                             : "[Still] Basket Ball",
        "/still/cr13.png"                              : "[Still] Bat",
        "/still/orient_beans.png"                      : "[Still] Beans",
        "/still/bell-pepper.png"                       : "[Still] Bell Pepper",
        "/still/anitpicker-icon.png"                   : "[Still] Bird 1",
        "/still/awalking-buzzard-icon.png"             : "[Still] Bird 2",
        "/still/zzzblank.png"                          : "[Still] Blank",
        "/still/clown.png"                             : "[Still] Blue Clown",
        "/still/blue.png"                              : "[Still] Blue Eyes",
        "/still/blue-robot.png"                        : "[Still] Blue Robot",
        "/still/cbowl.png"                             : "[Still] Bowl",
        "/still/brain.png"                             : "[Still] Brain",
        "/still/british_flag.png"                      : "[Still] British Flag",
        "/still/bubbles.png"                           : "[Still] Bubbles 1",
        "/still/design0019.png"                        : "[Still] Bubbles 2",
        "/still/abug.png"                              : "[Still] Bug",
        "/still/bus.png"                               : "[Still] Bus",
        "/still/canada_flag.png"                       : "[Still] Canada Flag",
        "/still/vase1.png"                             : "[Still] Candle Stick",
        "/still/carrot.png"                            : "[Still] Carrot",
        "/still/0apinkcat.png"                         : "[Still] Cat",
        "/still/cherry.png"                            : "[Still] Cherry",
        "/still/chick.png"                             : "[Still] Chicken",
        "/still/design0011.png"                        : "[Still] Circuit Board",
        "/still/ocity.png"                             : "[Still] City Skyline",
        "/still/climbing.png"                          : "[Still] Climbing a Ladder",
        "/still/closed.png"                            : "[Still] Closed",
        "/still/code.png"                              : "[Still] Code 1",
        "/still/design0020.png"                        : "[Still] Code 2",
        "/still/powerup2.png"                          : "[Still] Coffee",
        "/still/zthree-circles.png"                    : "[Still] Color Circles",
        "/still/cookiemonster.png"                     : "[Still] Cookie Monster",
        "/still/cr32.png"                              : "[Still] Crab 1",
        "/still/crab.png"                              : "[Still] Crab 2",
        "/still/g34.png"                               : "[Still] Crab 3",
        "/still/g39.png"                               : "[Still] Crab 4",
        "/still/cucumber.png"                          : "[Still] Cucumber",
        "/still/dinosaur.png"                          : "[Still] Dinosaur 1",
        "/still/trex.png"                              : "[Still] Dinosaur 2",
        "/still/cr06.png"                              : "[Still] Dog 1",
        "/still/cr09.png"                              : "[Still] Dog 2",
        "/still/dog.png"                               : "[Still] Dog 3",
        "/still/cr12.png"                              : "[Still] Eel",
        "/still/aeggplant-bonus-icon.png"              : "[Still] Eggplant",
        "/still/cr27.png"                              : "[Still] Elephant",
        "/still/elmo.png"                              : "[Still] Elmo",
        "/still/red1.png"                              : "[Still] Emoji 1",
        "/still/red2.png"                              : "[Still] Emoji 2",
        "/still/red3.png"                              : "[Still] Emoji 3",
        "/still/red4.png"                              : "[Still] Emoji 4",
        "/still/red6.png"                              : "[Still] Emoji 5",
        "/still/red7.png"                              : "[Still] Emoji 6",
        "/still/red10.png"                             : "[Still] Emoji 7",
        "/still/red11.png"                             : "[Still] Emoji 8",
        "/still/red12.png"                             : "[Still] Emoji 9",
        "/still/red13.png"                             : "[Still] Emoji 10",
        "/still/0aagtongue32.png"                      : "[Still] Eye",
        "/still/face.png"                              : "[Still] Face 1",
        "/still/face2.png"                             : "[Still] Face 2",
        "/still/face4.png"                             : "[Still] Face 3",
        "/still/girlglasses.png"                       : "[Still] Face 4",
        "/still/greeneyes.png"                         : "[Still] Face 5",
        "/still/guy5.png"                              : "[Still] Face 6",
        "/still/lady55.png"                            : "[Still] Face 7",
        "/still/vase2.png"                             : "[Still] Face 8",
        "/still/aasmile5.png"                          : "[Still] Face 9",
        "/still/rlady.png"                             : "[Still] Face 10",
        "/still/redlady.png"                           : "[Still] Face 11",
        "/still/shake2.png"                            : "[Still] Fight",
        "/still/design0007.png"                        : "[Still] Fire",
        "/still/fireball.png"                          : "[Still] Fireball 1",
        "/still/aanother-fireball-icon.png"            : "[Still] Fireball 2",
        "/still/aanother-hammerable-fireball-icon.png" : "[Still] Fireball 3",
        "/still/blue-fish.png"                         : "[Still] Fish 1",
        "/still/fish1.png"                             : "[Still] Fish 2",
        "/still/fishing.png"                           : "[Still] Fishing 1",
        "/still/fishmen.png"                           : "[Still] Fishing 2",
        "/still/blueflower.png"                        : "[Still] Flower 1",
        "/still/flower2.png"                           : "[Still] Flower 2",
        "/still/niceflowers.png"                       : "[Still] Flower 3",
        "/still/rose3.png"                             : "[Still] Flower 4",
        "/still/orient_flower2.png"                    : "[Still] Flower 5",
        "/still/flying_pig.png"                        : "[Still] Flying Pig",
        "/still/cr15.png"                              : "[Still] Fox",
        "/still/frankenstein-icon.png"                 : "[Still] Frankenstein",
        "/still/frog.png"                              : "[Still] Frog",
        "/still/froggy.png"                            : "[Still] Froggy",
        "/still/fruit_bowl.png"                        : "[Still] Fruit Bowl",
        "/still/fueltank.png"                          : "[Still] Fuel Tank",
        "/still/orient_ginseng.png"                    : "[Still] Ginseng Root",
        "/still/cr03.png"                              : "[Still] Goat",
        "/still/cr10.png"                              : "[Still] Gorilla",
        "/still/greece.png"                            : "[Still] Greece",
        "/still/greenplant.png"                        : "[Still] Green Plant",
        "/still/aaagumball.png"                        : "[Still] Gumball Machine",
        "/still/hand.png"                              : "[Still] Hand",
        "/still/shake1.png"                            : "[Still] Handshake",
        "/still/design0025.png"                        : "[Still] Hearts 1",
        "/still/heartface.png"                         : "[Still] Hearts 2",
        "/still/design0028.png"                        : "[Still] Home Sweet Home",
        "/still/cr25.png"                              : "[Still] Horse 1",
        "/still/orient_horse.png"                      : "[Still] Horse 2",
        "/still/design0008.png"                        : "[Still] Hourglass",
        "/still/fly.png"                               : "[Still] Housefly",
        "/still/cr05.png"                              : "[Still] Hummingbird",
        "/still/achicken-intruder-icon.png"            : "[Still] Intruder",
        "/still/jellybean.png"                         : "[Still] Jelly Beans",
        "/still/cr29.png"                              : "[Still] Jelly Fish",
        "/still/little_knight.png"                     : "[Still] Knight",
        "/still/lipstick.png"                          : "[Still] Lipstick",
        "/still/cr26.png"                              : "[Still] Lizard",
        "/still/orient_lotus.png"                      : "[Still] Lotus Root",
        "/still/design0027.png"                        : "[Still] Magma",
        "/still/maid.png"                              : "[Still] Maid",
        "/still/arobotronguy.png"                      : "[Still] Man",
        "/still/mario.png"                             : "[Still] Mario 1",
        "/still/mushroom.png"                          : "[Still] Mario 2",
        "/still/pooka.png"                             : "[Still] Mario Pooka",
        "/still/question.png"                          : "[Still] Mario Question Box",
        "/still/ared-snapjaw-icon.png"                 : "[Still] Mario Snapjaw",
        "/still/miner.png"                             : "[Still] Miner",
        "/still/moai2.png"                             : "[Still] Moai",
        "/still/monalista.png"                         : "[Still] Mona Lisa",
        "/still/cr14.png"                              : "[Still] Monkey",
        "/still/moustache.png"                         : "[Still] Moustache and Top Hat 1",
        "/still/moustache---copy.png"                  : "[Still] Moustache and Top Hat 2",
        "/still/mspacman.png"                          : "[Still] Mrs. Pacman 1",
        "/still/amspacman.png"                         : "[Still] Mrs. Pacman 2",
        "/still/music-notes.png"                       : "[Still] Musical Notes",
        "/still/night_driving.png"                     : "[Still] Night Driving",
        "/still/night-sky.png"                         : "[Still] Night Sky",
        "/still/now-open.png"                          : "[Still] Now Open",
        "/still/obama.png"                             : "[Still] Obama",
        "/still/rsquid.png"                            : "[Still] Octopus",
        "/still/onion.png"                             : "[Still] Onion",
        "/still/orient_berries.png"                    : "[Still] Oriental Berries",
        "/still/orient_food.png"                       : "[Still] Oriental Food",
        "/still/ostrich.png"                           : "[Still] Ostrich",
        "/still/owl.png"                               : "[Still] Owl",
        "/still/aedible-ghost-icon.png"                : "[Still] Pacman Ghost 1",
        "/still/aspeedy-pinky-icon.png"                : "[Still] Pacman Ghost 2",
        "/still/pacmean.png"                           : "[Still] Pacman Ghost 3",
        "/still/pacmanpink.png"                        : "[Still] Pacman Ghost 4",
        "/still/apacman2.png"                          : "[Still] Pacman Ghost 5",
        "/still/cr07.png"                              : "[Still] Parrot",
        "/still/pharmacy.png"                          : "[Still] Pharmacy",
        "/still/phonogrph-.png"                        : "[Still] Phonograph",
        "/still/pineapple.png"                         : "[Still] Pineapple",
        "/still/orient_plant2.png"                     : "[Still] Plant 1",
        "/still/orient_plant4.png"                     : "[Still] Plant 2",
        "/still/possum.png"                            : "[Still] Possum",
        "/still/qr-pixel.png"                          : "[Still] QR Code 1",
        "/still/qrpink.png"                            : "[Still] QR Code 2",
        "/still/awhite-race-car-icon.png"              : "[Still] Race Car",
        "/still/cr24.png"                              : "[Still] Ram",
        "/still/redswirl.png"                          : "[Still] Red Swirl",
        "/still/cr04.png"                              : "[Still] Rhinoceros",
        "/still/Robot.png"                             : "[Still] Robot 1",
        "/still/redrobot.png"                          : "[Still] Robot 2",
        "/still/aberzerk3.png"                         : "[Still] Robot 3",
        "/still/arobotron1.png"                        : "[Still] Robotron 1",
        "/still/arobotron2.png"                        : "[Still] Robotron 2",
        "/still/arobotron3.png"                        : "[Still] Robotron 3",
        "/still/gfahahae.png"                          : "[Still] Running",
        "/still/arutabaga-bonus-icon.png"              : "[Still] Rutabaga",
        "/still/cr11.png"                              : "[Still] Scorpion",
        "/still/cr01.png"                              : "[Still] Seahorse",
        "/still/cr31.png"                              : "[Still] Seal",
        "/still/skeleton.png"                          : "[Still] Skeleton",
        "/still/spaceinvader.png"                      : "[Still] Space Invader",
        "/still/abosconian-icon.png"                   : "[Still] Spaceship 1",
        "/still/flagship.png"                          : "[Still] Spaceship 2",
        "/still/agalaxian-bonus-icon.png"              : "[Still] Spaceship 3",
        "/still/agalaxip-icon.png"                     : "[Still] Spaceship 4",
        "/still/ai-type-missle-icon.png"               : "[Still] Spaceship 5",
        "/still/insect-icon.png"                       : "[Still] Spaceship 6",
        "/still/ajet-icon"                             : "[Still] Spaceship 7",
        "/still/mystery-base-icon.png"                 : "[Still] Spaceship 8",
        "/still/aspy-ship-icon.png"                    : "[Still] Spaceship 9",
        "/still/ptype.png"                             : "[Still] Spaceship 10",
        "/still/invader1b.png"                         : "[Still] Space Invaders 1",
        "/still/invader5.png"                          : "[Still] Space Invaders 2",
        "/still/g33.png"                               : "[Still] Spider",
        "/still/squidy.png"                            : "[Still] Squidy",
        "/still/cr16.png"                              : "[Still] Squirrel",
        "/still/suit.png"                              : "[Still] Suit and Tie",
        "/still/sunset.png"                            : "[Still] Sunset",
        "/still/defender.png"                          : "[Still] Sword",
        "/still/atractor-icon.png"                     : "[Still] Tractor",
        "/still/orient_tree.png"                       : "[Still] Tree Stump",
        "/still/trophy.png"                            : "[Still] Trophy",
        "/still/cr02.png"                              : "[Still] Turtle 1",
        "/still/aturtle-icon.png"                      : "[Still] Turtle 2",
        "/still/zcolortest.png"                        : "[Still] TV Color Bars",
        "/still/aufo-icon.png"                         : "[Still] UFO",
        "/still/umbrella.png"                          : "[Still] Umbrella",
        "/still/vgame.png"                             : "[Still] Video Game",
        "/still/pops.png"                              : "[Still] Whac-A-Mole",
        "/still/adig-dug-digging-icon.png"             : "[Still] Warrior 1",
        "/still/hwarrior.png"                          : "[Still] Warrior 2",
        "/still/ywarrior.png"                          : "[Still] Warrior 3",
        "/still/watermelon.png"                        : "[Still] Watermelon 1",
        "/still/awatermelon-bonus-icon.png"            : "[Still] Watermelon 2",
        "/still/g40.png"                               : "[Still] Whale",
        "/still/orient_barrell.png"                    : "[Still] Wheelbarrow",
        "/still/zzzwhite.png"                          : "[Still] White",
        "/still/window2.png"                           : "[Still] Window",
        "/still/wizard_mountain.png"                   : "[Still] Wizard",
        "/still/arobotrongirl.png"                     : "[Still] Woman"
      ],
      title: "Image",
      description: "Image or animation to display when on")
  }
}

def parse(String description) {
  log.debug "Parsing '${description}'"
}

def on() {
  log.debug("Executing 'on'")
  urlRequest(image)
  sendEvent(name: "switch", value: "on")
}

def off() {
  log.debug("Executing 'off'")
  urlRequest("/still/zzzblank.png")
  sendEvent(name: "switch", value: "off")
}

private def urlRequest(String path) {
  def params = [
    uri: url,
    path: path
  ]
  
  if(external == "External") {
    log.debug("Making external call")
    
    try {
      httpGet(params) {
        log.debug("Finished external call")
      }
    } catch (e) {
      log.error("Could not make external call")
    }
      
    return
  }
  
  log.debug("Making internal call")
  
  def action = new physicalgraph.device.HubAction(
    method: "GET",
    path: params["path"],
    headers: [
      "Host": params["uri"]
    ]
  )
  
  sendHubCommand(action)
}
